### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ghost** [libimobiledevice/libimobiledevice#615] opened 2018-02-01 22:54 UTC
How to compile libimobiledevice i need help

**Comment by samrocketman** [comment] 2018-02-02 06:04
If you're asking about how to compile on Linux or Mac OS X then refer to this gist -> https://gist.github.com/samrocketman/70dff6ebb18004fc37dc5e33c259a0fc

**Comment by vladut123** [comment] 2018-02-02 09:49
How to compile otachecker-master

**Comment by vladut123** [comment] 2018-02-02 09:56
Disable iphone charging when connected to macbook

**Comment by vladut123** [comment] 2018-02-03 15:03
How to compile libimobiledevice on mac

**Comment by vladut123** [comment] 2018-02-03 15:04
How to compile img4tool on windows 10

**Comment by nikias** [comment] 2018-02-03 21:24
Please stop asking random questions. otachecker and img4tool are completely different projects.

**Comment by FunkyM** [comment] 2020-06-15 23:14
Closing as duplicate of #620.

**Closed by FunkyM** 2020-06-15 23:14 UTC
