### ISSUE TITLE
idevicebackup2 errorcode -6

### ISSUE THREAD

**Issue by Kanong017** [libimobiledevice/libimobiledevice#500] opened 2017-05-07 08:59 UTC
how to fix it?
pls help me

**Comment by samrocketman** [comment] 2017-05-07 09:32
As noted in #468, you need to compile the latest sources.  This is not a bug because it has been fixed in master.

**Comment by Kanong017** [comment] 2017-05-07 09:36
@samrocketman I was using the latest version of the compiler, or error code -6

**Comment by nikias** [comment] 2017-05-07 11:10
duplicate of #490 and #491

**Closed by nikias** 2017-05-07 11:10 UTC

**Comment by samrocketman** [comment] 2017-05-07 17:21
@Kanong017 subscribe to #490 for updates.
