### ISSUE TITLE
com.apple.mobilebackup2 could not start

### ISSUE THREAD

**Issue by k1priest** [libimobiledevice/libimobiledevice#266] opened 2015-12-11 23:00 UTC
Hello, i was trying to do the bypass trick with backups but when i try to restore the backup it gives me this error:
"could not start service com.apple.mobilebackup2".
Thank you!
PS: im on windows 8 btw.

**Comment by girlMP** [comment] 2016-01-18 05:02
BUMP... Also want to know how to fix the com.apple.mobilebackup2 error

**Comment by trejo08** [comment] 2017-06-10 06:11
Also I'm trying to fix that error, if someone knows how to fix it please tell me.

Thanks

**Comment by LetsUnlockiPhone** [comment] 2017-09-28 21:23
you need to activate your device first
com.apple.mobilebackup wont start till your device pass activation

**Comment by nikias** [comment] 2017-09-28 21:46
Not a bug in libimobiledevice. Closing.

**Closed by nikias** 2017-09-28 21:46 UTC
