### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anatoli26** [libimobiledevice/libimobiledevice#456] opened 2017-01-21 04:19 UTC
Please release a new version and notify the distributions to include it, the latest was published 2 years ago, a lot of things are not working in stock distro installations (v1.2.0) that are working with manually compiled binaries from the HEAD.

**Comment by TheElectronWill** [comment] 2017-01-23 19:05
This has already been asked multiple times (but there is still no official release :| ).
If you use Fedora, Ubuntu or a derivative, I've put some useful links for you in the comments of issue #380

**Comment by anatoli26** [comment] 2017-01-25 01:00
@TheElectronWill, thanks for the information and the links. I've just checked all related issues asking for a new release, but haven't found any answer from the maintainers. At the same time I see that the project has recent updates, so it's not abandoned. Was there any explanation for no release for so long?

**Comment by songhaonangit** [comment] 2017-02-08 02:44
Please release a new version

**Comment by reaniwen** [comment] 2017-03-31 22:14
I think the best solution is to clone the newest version code and compile it locally.

**Comment by anatoli26** [comment] 2017-04-01 05:06
Sure, but it's not manageable on more that a couple of computers. Does anybody know why the maintainers don't release a new version?

**Comment by Mintyjack** [comment] 2017-04-01 08:26
There are increasing numbers of people like me who migrated from Windows and are not that tech savvy so can't compile their own 'release'. It's a shame, mint 18 was working fine for me till IOS 10.2. I want to support open source but issues like this make it difficult for 'ordinary Joe' type use.

I considered offering a bounty for a ppa of the latest version, but it's a sticking plaster, what happens when IOS 10.3 or whatever comes along?

**Comment by LinuxDonald** [comment] 2017-04-01 11:34
@TheElectronWill maybe add it to the wiki here? Maybe then we could add more script for making own packages?

**Comment by TamimiGitHub** [comment] 2017-04-07 18:32
@FunkyM Do you guys have any plans to release a new version? As of right now, there are a couple of fixed that came in after 1.2 and we have been using `brew install libimobiledevice --HEAD` to make sure fixes are in. It will be great if we can get an update on this release.
Thanks

**Comment by samrocketman** [comment] 2017-04-26 04:55
For those who can't wait for a release, I've published a guide of how I built libimobiledevice for myself.  Perhaps you may benefit.  https://gist.github.com/samrocketman/70dff6ebb18004fc37dc5e33c259a0fc

**Comment by franklinyu** [comment] 2017-11-01 21:53
Duplicate of #380

**Comment by FunkyM** [comment] 2020-06-15 23:04
Closing as version [1.3.0](/libimobiledevice/libimobiledevice/releases/tag/1.3.0) has been released.

**Closed by FunkyM** 2020-06-15 23:04 UTC
